# ===============================
# Upptime configuration
# ===============================

owner: cristix415      # contul tău GitHub
repo: Uptime2          # numele repository-ului tău

sites:
  - name: Bedstyle
    url: https://www.bedstyle.ro
  - name: Smartstyle
    url: https://www.smartstyle.ro

status-website:
  cname: demo.upptime.js.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our GitHub repository. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# ===============================
# Telegram Notifications
# ===============================
notifications:
  - type: custom
    env:
      BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    on:
      - status-change   # trimite notificare când un site devine up/down
    run: |
      SITE="${SITE_NAME:-Unknown site}"
      STATUS="${STATUS:-Unknown status}"
      MESSAGE="🖥️ Site: $SITE\nStatus: $STATUS"
      curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
        -d chat_id=$CHAT_ID \
        -d text="$MESSAGE"
